### ISSUE TITLE
Landrush prevents the machine from reaching internet

### ISSUE THREAD

**Issue by lgueye** [vagrant-landrush/landrush#11]
I launched vagrant-omnibus on my newly configured machine and it could not reach opscode.com.

When I disabled lanrush, my vm could reach opscode.com again ...

``` ruby
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu-server-12.10"
  config.vm.box_url = "http://goo.gl/wxdwM"
  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  #config.landrush.enable

  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", "512"]
    vbox.customize ["modifyvm", :id, "--cpus", "2"]
    vbox.customize ["modifyvm", :id, "--ioapic", "on"]
    vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vbox.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # Database
  databases = "#{app_name}-mysql"
  config.vm.define databases do |mysql|
    mysql.vm.hostname = databases
    mysql.vm.network :private_network, ip: "192.168.10.1"

    mysql.vm.provider :virtualbox do |vbox|
      vbox.name = "#{mysql.vm.hostname}"
    end

    mysql.vm.provision "chef_solo" do |chef|
      chef.add_recipe "apt"
      chef.json = {
          "mysql" => {
              "server_root_password" => "*mysql-limber@0",
              "server_debian_password" => "*mysql-limber@0",
              "server_repl_password" => "*mysql-limber@0"
          }
      }
      chef.add_recipe "mysql::server"
    end
  end
end
```

**Comment by danielsand** [comment]
just run into this one.

best thing to provoke the error is to set a different natnet instead of 10.0.2.
```
config.customize ["modifyvm", :id, "--natnet1", "192.168/16"]
```
dns is then not working from inside of the vm. As soon i remove the natnet or disable landrush - All is working again.

**Comment by danielsand** [comment]
the problem is here

'''
https://github.com/phinze/landrush/blob/710a18284a2136c1f5517f6a63e62885ba0e42ad/lib/landrush/action/redirect_dns.rb
'''

for virtualbox its always '10.0.2.2' - which will fail if you have a different network setting.
Tested it by hand... works if i change it to my new natnetwork.

'''
 def _target_host
        case provider
        when :virtualbox then
          '10.0.2.2'
'''

sorry i couldnt provide a fix - im not really keen on vagrant internals to find out the current ip and gateway ip. :/

**Comment by paulccarey** [comment]
+1 I also have this issue. Tried @danielsand suggestions with no luck but tbh didnt really understand the implications tbh.
Disabling landrush for now, would be great to get a fix, happy to help with this also if someone can give me some background I'd be happy to create a PR.

**Comment by ianmiell** [comment]
Am having a similar problem with kvm, and am wondering if it's because I'm setting the private ip address in my Vagrantfile.

**Comment by ianmiell** [comment]
Confirmed. Removing private ips works fine for me.
