### ISSUE TITLE
How do I remove vms entries?

### ISSUE THREAD

**Issue by bertramn** [vagrant-landrush/landrush#126]
I have vagrant 1.7 configured with landrush on OSX and noticed that `vagrant landrush vms` is clobbered with old VMs that I abandoned. They do not show up in the `vagrant landrush ls` command and I cannot remove them with `vagrant landrush rm xxxx` either. Maybe a bug? Does anyone know how to get rid of vms entries? Many thanks N

**Comment by njam** [comment]
Hm, `vagrant landrush rm <hostname>` works for me.
What version are you using?
Can you check if those entries are present in `~/.vagrant.d/data/landrush/hosts.json`?

**Comment by njam** [comment]
Closing due to lack of feedback.
@bertramn please reopen if you're still experiencing this issue.
