### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by babilen** [vagrant-landrush/landrush#162]
The last landrush release has been made quite some time ago and a number of important changes have found their way into the git reposity. Unfortunately it is tricky to take advantage of them in vagrant, due to them not having been released yet. Are there any plans for cutting a new release soon(ish) ?

Thank you!

**Comment by bexelbie** [comment]
There is a meeting of the current committers next week and this is a conversation item.  I will be pushing for 'yes'  So watch this space :)

**Comment by bexelbie** [comment]
@babilen we had a meeting last week and have published a release roadmap with rough timelines in the README.  @phinze is working on the first new release with an eye toward ensuring the new maintainers can all help with the next one.

May we close this issue?

**Comment by phinze** [comment]
Ha this was a good reminder for me - releasing now and will close this issue when it's out. :+1: :smile:

**Comment by phinze** [comment]
Done and done!

**Comment by babilen** [comment]
Wonderful! Congratulations, much appreciated! :)
