### ISSUE TITLE
Using landrush with middleman?

### ISSUE THREAD

**Issue by jessepollak** [vagrant-landrush/landrush#173]
I'm creating a new static site with middleman. It's not in a Vagrant box, but I'm still interested in using landrush to mange the DNS (so I can have it at the same TLD as our other boxes).

Any thoughts on the best way to do this (or if it's even a good idea)?

**Comment by njam** [comment]
You could run:
```
vagrant landrush start
vagrant landrush set <ip> <host>
```
Not super convenient, but could be embedded into other scripts? (I don't know middleman…)

**Comment by jessepollak** [comment]
Ah, that's awesome — didn't realize I could invoke it with `vagrant landrush`, thank you!
