### ISSUE TITLE
Intermittently guest stops resolving domains

### ISSUE THREAD

**Issue by Dylan1312** [vagrant-landrush/landrush#179]
Hey there,

Landrush usually works fine, however intermittently the guest OS (CentOS6) will stop being able to resolve domains, hanging instead - this is fixed with running "vagrant landrush restart" on the host.

Would you guys be able to point me to any log files or places I should be looking to investigate further? /etc/resolv.conf keeps pointing to the same place and my IPTables aren't changing.

Thanks!

**Comment by njam** [comment]
Landrush logs are in `~/.vagrant.d/data/landrush/log/`.
In such situation is the landrush process still running?

**Comment by Dylan1312** [comment]
Hey @njam, thanks!

The landrush process is indeed still running on the host (OSX 10.10.1). I'll dig further but here's what I'm seeing in the logs -

On initial failure:
`I, [2016-04-20T18:17:07.866238 #20773]  INFO -- : Starting RubyDNS server (v1.0.2)...
I, [2016-04-20T18:17:07.866565 #20773]  INFO -- : <> Listening on udp:0.0.0.0:10053
I, [2016-04-20T18:17:07.868622 #20773]  INFO -- : <> Listening on tcp:0.0.0.0:10053
E, [2016-04-20T18:41:31.994691 #20773] ERROR -- : Actor crashed!
Errno::ENETUNREACH: Network is unreachable - sendto(2) for "192.168.200.53" port 53
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:223:in `try_udp_server'
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:197:in `try_server'
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:157:in `block (2 levels) in dispatch_request'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid.rb:407:in `block in timeout'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/actor.rb:252:in `timeout'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid.rb:406:in `timeout'
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:156:in `block in dispatch_request'
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:284:in `block in each'
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:281:in `each'
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:281:in `each'
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:147:in `dispatch_request'
	/Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/resolver.rb:93:in `query'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create

E, [2016-04-20T18:41:31.994999 #20773] ERROR -- : <24874> Exception thrown while processing syslog001.INTERNAL Resolv::DNS::Resource::IN::A!
E, [2016-04-20T18:41:31.995473 #20773] ERROR -- : Errno::ENETUNREACH: Network is unreachable - sendto(2) for "192.168.200.53" port 53'
E, [2016-04-20T18:41:31.994999 #20773] ERR`

Then on further requests

`E, [2016-04-20T18:41:36.996806 #20773] ERROR -- : <24874> Exception thrown while processing syslog001.INTERNALResolv::DNS::Resource::IN::A!
E, [2016-04-20T18:41:36.997835 #20773] ERROR -- : Celluloid::DeadActorError: attempted to call a dead actor
E, [2016-04-20T18:41:36.998179 #20773] ERROR -- : /Users/dylan/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:23:in `method_missing'
E, [2016-04-20T18:41:36.998302 #20773] ERROR -- : /Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/transaction.rb:109:in `passthrough'
E, [2016-04-20T18:41:36.998387 #20773] ERROR -- : /Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/transaction.rb:83:in `passthrough!'
E, [2016-04-20T18:41:36.998469 #20773] ERROR -- : /Users/dylan/.vagrant.d/gems/gems/landrush-0.19.0/lib/landrush/server.rb:71:in `block (2 levels) in run'
E, [2016-04-20T18:41:36.998551 #20773] ERROR -- : /Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/server.rb:217:in `[]'
E, [2016-04-20T18:41:36.998632 #20773] ERROR -- : /Users/dylan/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/server.rb:217:in `call'`

**Comment by Dylan1312** [comment]
Actually looks like this is covered in

https://github.com/vagrant-landrush/landrush/issues/107

Feel free to close

**Comment by njam** [comment]
Ok, thanks for investigating!
