### ISSUE TITLE
Please add other maintainers to rubygems.org

### ISSUE THREAD

**Issue by bexelbie** [vagrant-landrush/landrush#185]
@phinze ^^

**Comment by phinze** [comment]
Just did `gem owner --add {email} landrush` for all the email addresses I have. Looks like it worked for @bexelbie @ahpook and @strzibny, but not for the rest.

@njam, @fh, @hferentschik - can you hit me with your rubygems email addresses and I'll get you added too?

**Comment by njam** [comment]
reto@retokaiser.com - https://rubygems.org/profiles/njam

**Comment by hferentschik** [comment]
@phinze - hardy at ferentschik.de (https://rubygems.org/profiles/hardy)

**Comment by bexelbie** [comment]
@hferentschik I've added you.  @njam it appears that @phinze added you.
