### ISSUE TITLE
Release of Landrush 1.0.0

### ISSUE THREAD

**Issue by hferentschik** [vagrant-landrush/landrush#186]
@bexelbie, @ahpook, @fh, @strzibny, @phinze, @njam - any objections if I cut a 1.0.0 release

**Comment by bexelbie** [comment]
Are there any pending PRs you want to include?

**Comment by hferentschik** [comment]
> Are there any pending PRs you want to include?

Not for now. Both open pull requests are still under discussion

**Comment by bexelbie** [comment]
+1 for 1.0 with current code and no additional PRs .. if PRs land that is OK too.  Do you need help with this?

**Comment by njam** [comment]
sgtm!

**Comment by ahpook** [comment]
:+1:

**Comment by hferentschik** [comment]
Cool. I do it once I get access to RubtGems
