### ISSUE TITLE
landrush-1.1.2

### ISSUE THREAD

**Issue by bexelbie** [vagrant-landrush/landrush#253]
I am preparing to release landrush-1.1.2.  I'd like to push it tomorrow (Tuesday 23 August) or Wednesday.  Do you have any PRs or concerns?

I have merged #249, #247, and #243

@ahpook @fh @hferentschik @strzibny @phinze @njam

**Comment by njam** [comment]
https://github.com/vagrant-landrush/landrush/pull/246 pleeease :) cc @hferentschik

**Comment by fh** [comment]
👍

**Comment by bexelbie** [comment]
@njam @hferentschik is offline on vacation and is only occasionally online.  I'll try to review #246 today.

**Comment by njam** [comment]
Thank you! Otherwise we can do two releases.

**Comment by bexelbie** [comment]
@hferentschik would like #247 reverted for further discussion.  I will do this.  #246 will not make this release.
