### ISSUE TITLE
Upstream DNS should not default to 8.8.8.8

### ISSUE THREAD

**Issue by bexelbie** [vagrant-landrush/landrush#254]
I work in an environment where unapproved DNS requests are blocked.  Therefore landrush breaks for me in its default configuration.

I believe that the default should be to use the upstream resolvers as specified on the host and that 8.8.8.8 should only be used as a fall back.

For Linux, this should be what is in /etc/resolv.conf.  I'd need to check OS X, but I believe the same is true.  I am not sure about Windows.

comments?

**Comment by njam** [comment]
Agree!

I think it's the same as https://github.com/vagrant-landrush/landrush/issues/60 ?

**Comment by bexelbie** [comment]
Yes, it is similar to #60 - oops.
