### ISSUE TITLE
Convert documentation to asciidoc

### ISSUE THREAD

**Issue by hferentschik** [vagrant-landrush/landrush#264]

**Comment by hferentschik** [comment]
While on it, I think it makes sense to split up the README into multiple documented, eg _usage_, _development_, _faq_. The documents should then go into the _doc_ folder.

**Comment by hferentschik** [comment]
@Preeticp, is this something you can look into?

**Comment by Preeticp** [comment]
Sure

**Comment by hferentschik** [comment]
@Preeticp 

> Sure

Great. As mentioned in this issue lets convert to asccidoc and split the content while at it. Once we have this, I am planning to add some more content (like the various config files etc).

**Comment by hferentschik** [comment]
Resolved by pull request #291
