### ISSUE TITLE
"host_interface" ignored if only 1 private interface is configured

### ISSUE THREAD

**Issue by njam** [vagrant-landrush/landrush#268]
If only 1 private, but further public interfaces are configured:
```
    config.vm.network :private_network, ip: '10.10.11.10'
    config.vm.network :public_network, :bridge => 'en0: Wi-Fi (AirPort)'
```

and we want to use the public interface for landrush:
```
config.landrush.host_interface = 'eth2'
```

That configuration is ignored, because landrush assumes the private interface to be the desired one.

**Comment by hferentschik** [comment]
Merged.
