### ISSUE TITLE
Vagrant 1.9.0 / OSX 10.12.1 - Ignoring eventmachine-1.0.9.1 because its extensions are not built

### ISSUE THREAD

**Issue by nervo** [vagrant-landrush/landrush#292]
I have just tried to install landrush on a fresh vagrant 1.9.0 install on OSX 10.12.1
Nothings to notice in particular except "Building native extensions"

```
$ vagrant plugin install landrush --verbose
Installing the 'landrush' plugin. This can take a few minutes...
Fetching: eventmachine-1.0.9.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: landrush-ip-0.2.5.gem (100%)
Fetching: win32-process-0.8.3.gem (100%)
Fetching: rubydns-0.8.5.gem (100%)
Fetching: landrush-1.1.2.gem (100%)
```

Right after, every vagrant command sends a warning...

```
$ vagrant ssh
Ignoring eventmachine-1.0.9.1 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.9.1
```

... and daemon refuse to start

```
$ vagrant landrush start
Ignoring eventmachine-1.0.9.1 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.9.1
$ vagrant landrush status
Ignoring eventmachine-1.0.9.1 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.9.1
Daemon status: unknown
/Users/[...]/.vagrant.d/data/landrush/run/landrush.pid exists, but process is not running
Check log file: /Users/[...]/.vagrant.d/data/landrush/log/landrush.log
```

landrush.log is empty...

**Comment by Bekt** [comment]
Experiencing the same thing. Reverting back to vagrant 1.8.6 works.

**Comment by nervo** [comment]
Embedded ruby version looks like the same in vagrant 1.8.7 and 1.9.0: ruby 2.2.5p319

**Comment by designtesbrot** [comment]
Reproduced on Ubuntu 14.04 using vagrant 1.9.0 and landrush 1.1.2

**Comment by nervo** [comment]
Maybe related to this: https://github.com/vagrant-landrush/landrush/issues/295 ?

**Comment by hferentschik** [comment]
For now Landrush is not compatible with Vagrant 1.9.0. Vagrant 1.9.0 made quite some substantial internal changes, which we need to look into. Most importantly it does not rely on Bundler anymore.

I am about to release Landrush 1.2.0 which will make Landrush compatible with Vagrant up to 1.8.6, after that we will be looking into getting a Landrush release which aligns with Vagrant 1.9

**Comment by jamroks** [comment]
Hi,

 I'm experiencing the same issue, thanks for the time you put into maintaining this plugin which is cool
 but would be great to have some kind of visibility into the release of the 1.9 vagrant compatibility on vagrant-landrush side . thanks

**Comment by rtvenge** [comment]
I'm not 100% sure what (if any) of these steps fixed this issue, but I was able to get the warning to go away. 

* Updated to Vagrant 1.9.7
* ran `vagrant plugin repair`

My thought it was the repair command but I can't know for sure. Hopefully that helps someone out.

**Comment by hferentschik** [comment]
I think this issue is out of date. The HEAD of Landrush is now on 2.1.4 and I am not able to reproduce this.
