### ISSUE TITLE
invalid byte sequence in UTF-8 on non-english windows platform

### ISSUE THREAD

**Issue by Valgard** [vagrant-landrush/landrush#309]
landrush raises an exception on my german windows 10 with following message

.../.vagrant.d/gems/2.2.5/gems/landrush-1.2.0/lib/landrush/cap/host/windows/configure_visibility_on_host.rb:150:in `wired_autoconfig_service_running?': invalid byte sequence in UTF-8 (ArgumentError)

**Comment by hferentschik** [comment]
I think this is a duplicate of #310.
