### ISSUE TITLE
wired_autoconfig_service_running does not recognize running service on non-english windows platform

### ISSUE THREAD

**Issue by Valgard** [vagrant-landrush/landrush#310]
in my german windows 10 landrush does not recognize the running 'Wired AutoConfig' service:

[landrush] Using eth1 (x.x.x.x)
[landrush] starting 'Wired AutoConfig' service
Systemfehler 5 aufgetreten.

Zugriff verweigert

[landrush] Unable to start 'Wired AutoConfig' service. Unable to configure DNS on host. Try manual configuration.

**Comment by a1ee9b** [comment]
I ran into the same problem. Try running Powershell or Cygwin as administrator.

**Comment by tomcbe** [comment]
I ran into the same problem. I created a pull request to address this issue.

**Comment by hferentschik** [comment]
Merged via pull request #326
