### ISSUE TITLE
RubyDNS 2.0.0 available

### ISSUE THREAD

**Issue by ioquatix** [vagrant-landrush/landrush#312]
This update is a big improvement to stability, if you have time to try it out and report any issues that would be great.

It might fix some of the issues you are having with IPv6/EventMachine, since EventMachine is no longer used.

**Comment by ioquatix** [comment]
Please consider updating and let me know any feedback. Thanks.

**Comment by jalcine** [comment]
Perhaps a PR to see the impact that can have?? @ioquatix

**Comment by hferentschik** [comment]
FYI, the reason RubyDNS is locked on 0.8.5 is that this was afair the last version based on eventmachine. A long time ago I tried to upgrade to a later RubyDNS version and I experienced hangups (I believe on Windows). eventmachine was the easier way forward at that point. 

Definitely worth giving it another try. The library probably has matured a lot. We should make sure to run some load tests to make sure there are no hangups.
