### ISSUE TITLE
Handle multi-user environments

### ISSUE THREAD

**Issue by madAndroid** [vagrant-landrush/landrush#315]
Hi,

We're seeing an issue when using vagrant in a non-standard environment:
Vagrant itself is able to handle running on a server with multiple user accounts, since it doesn't share global state between user accounts - so we are able to bring up multiple boxes for multiple users ..but as soon as one user destroys their boxes, the landrush server is destroyed, and it looks like this server is not namespaced, so it runs a single process for all users.

I realise this is a slighly unusual/non-standard approach, but we've got network and resource constraints which makes sharing a single server within a team easier than working on individual machines - would you consider a change which namespaces the landrush server so that it's isolated to a per-user process? this would solve our issue

**Comment by hferentschik** [comment]
I don't think this is feasible. There is no issue to spin up multiple Vagrant boxes, but the Landrush process is a single process running a DNS server. Not sure how one would namespace this. 

One could spin of a Landrush process per Vagrant box using dedicated ports per box. Visibility within the guest could probably be made to work, but I don't see how visibility on the host should be handled.

**Comment by madAndroid** [comment]
Fair point - I'll close this issue
