### ISSUE TITLE
Unable to start Landrush after upgrading to High Sierra

### ISSUE THREAD

**Issue by elepedus** [vagrant-landrush/landrush#318]
As the title says, Landrush has stopped working, possible as a result of upgrading to MacOS High Sierra. 

I've updated Vagrant to 2.0.1 and Landrush to 1.2.0, tried vagrant plugin repair as well as vagrant plugin expunge --reinstall to no effect.

`vagrant landrush status` says `landrush.pid exists, but process is not running. `
`vagrant landrush stop` says `Stopping daemon... Pid xxxx is not running. Has daemon crashed?`
`vagrant landrush start` says `[landrush] '/opt/vagrant/embedded/bin/ruby /Users/elepedus/.vagrant.d/gems/2.4.2/gems/landrush-1.2.0/lib/landrush/start_server.rb 10053 /Users/elepedus/.vagrant.d/data/landrush /Users/elepedus/.vagrant.d/gems/2.4.2/gems'` 

The process appears to get as far as creating the pid file and then silently crashes and VMs are not accessible through the browser.  `dig -p 10053 @localhost localdomain.local` says
```
; <<>> DiG 9.9.7-P3 <<>> -p 10053 @localhost localdomain.local
; (3 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 7833
;; flags: qr aa rd; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; Query time: 6 msec
;; SERVER: 127.0.0.1#10053(127.0.0.1)
;; WHEN: Tue Jan 09 14:10:01 GMT 2018
;; MSG SIZE  rcvd: 12
```
The log only has the following entries
```
I, [2018-01-09T14:07:14.374618 #4693]  INFO -- : Starting RubyDNS server (v0.8.5)...
I, [2018-01-09T14:07:14.374878 #4693]  INFO -- : Listening on udp:0.0.0.0:10053
```

Has anybody dealt with this before? I'm running out of ideas :/ 
  
EDIT: It appears that Landrush is running and the problem is somewhere else in my stack. However, the PID in the landrush.pid file does not appear to be correct, which is breaking the stop & status commands.

**Comment by gbraad** [comment]
We are currently investigating this also, since this matches the behaviour we are seeing with the new imlementation for Minishift. It looks like High Sierra does not allow traffic to traverse on any interface when in offline(/disconnected) mode.

**Comment by hferentschik** [comment]
I am unable to re-produce this.
