### ISSUE TITLE
Conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)

### ISSUE THREAD

**Issue by medined** [vagrant-landrush/landrush#333]
I don't know how to resolve this conflicting dependency issue. Please help.

Installing the 'landrush' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
  Activated fog-core-1.45.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 1.45.0), 1.45.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)

**Comment by hferentschik** [comment]
Are you sure this is a Landrush issue? AFAICT there is no dependency to fog-core in Landrush. Can you post the full error message? Is this happening when you do a `vagrant plugin install`? 
You can try to tp uninstall your plugins and re-install them? You can also try `vagrant plugin repair`.

**Comment by medined** [comment]
Thanks for replying. I'll be away from my computer for a week. I'll try to check when I get back.

**Comment by drmason13** [comment]
Hi, having the same issue.
This happens when running `vagrant plugin install`.
I am running vagrant version 2.0.2

```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
  Activated fog-core-1.45.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 1.45.0), 1.45.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)
```

I have plugin installed:

```
$ vagrant plugin list
vagrant-libvirt (0.0.43, system)
```

This appears to be causing the issue, but it is a part of vagrant, uninstalling doesn't seem to be an option:

```
$ vagrant plugin uninstall vagrant-libvirt
Uninstalling the 'vagrant-libvirt' plugin...
The plugin you're attempting to uninstall ('vagrant-libvirt') is a
system plugin. This means that the plugin is part of the installation
of Vagrant. These plugins cannot be removed.

You can however, install a plugin with the same name to replace
these plugins. User-installed plugins take priority over
system-installed plugins.
```

I tried updating also:

```
$ vagrant plugin update vagrant-libvirt
Updating plugins: vagrant-libvirt. This may take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-libvirt (> 0)'
```

So I'm guessing it is the latest version. I am running ubuntu 18.04 as the host.
Repair also had no joy. I'm conscious that this is probably our own system peculiarities, but I would appreciate some advice if you have any ideas.

**Comment by drmason13** [comment]
Yup! This seems to be an issue with our vagrant.

It's up to date according to apt but 2.0.3 should fix your issue if you are also experiencing this. A quick google search shows this problem in all sorts of vagrant plugins... [for example](https://github.com/dotless-de/vagrant-vbguest/issues/292)

From there, the suggestion is:

```
wget -c https://releases.hashicorp.com/vagrant/2.1.5/vagrant_2.0.3_x86_64.deb
sudo dpkg -i vagrant_2.1.5_x86_64.deb
```
(I swapped 2.0.3 for 2.1.5 the latest vagrant version at time of writing)

This fixed everything :)

```
$ vagrant plugin install landrush
Installing the 'landrush' plugin. This can take a few minutes...
Fetching: filelock-1.1.1.gem (100%)
Fetching: landrush-ip-0.2.5.gem (100%)
Fetching: eventmachine-1.0.9.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: rubydns-0.8.5.gem (100%)
Fetching: win32-process-0.8.3.gem (100%)
Fetching: landrush-1.3.0.gem (100%)
Installed the plugin 'landrush (1.3.0)'!
```

**Comment by hferentschik** [comment]
@drmason13 thanks for the heads-up

**Comment by rodrigoroccozoop** [comment]
drmason13, you left a mistake on your edit. The file name at wget is still 2.0.3
