### ISSUE TITLE
how do I override the .dev 

### ISSUE THREAD

**Issue by perthvader** [vagrant-landrush/landrush#34]
Sorry if this is the wrong place to ask, but I'm using landrush succesfully for my local environment. I currently want to move into production, using a different provider.

As I am new to salt and provisioning (and landrush) I am trying to understand how to override hostnames properly.. consider my setup:

```
Vagrant.configure("2") do |config|
  config.vm.define :salt do |node|
    node.vm.hostname = "salt.vagrant.dev"
  end
  config.vm.define :webserver01 do |node|
    node.vm.hostname = "webserver01.vagrant.dev"
  end
end
```

Should I create a different Vagrant file for production? There cant be two Vagrantfiles in one directory right.. Should I use some sort of overriding technique? I have tried w/o success..

This fails:
```
Vagrant.configure("2") do |config|

  config.vm.provider :my_cloud_host do |provider, override|
  end

  config.vm.define :salt do |node, override|
    override.vm.hostname = "salt.example.com"
  end

  config.vm.define :webserver01 do |node, override|
    override.vm.hostname = "webserver01.example.com"
  end

end
```

Sorry if this is a stupid question, I couldn't find proper directions in the vagrant docs..

**Comment by njam** [comment]
Closing this for now, TLD can be set with `config.landrush.tld`.

@perthvader please reopen if you're still experiencing problems with changing the TLD.
