### ISSUE TITLE
Unable to determine network interface on non-English Windows

### ISSUE THREAD

**Issue by davividal** [vagrant-landrush/landrush#344]
When using a Windows with a language different than English, `netsh` output will not be in English.

`lib/landrush/cap/host/windows/configure_visibility_on_host.rb` relies on `netsh` output being in English for it to correctly set the DNS server.

**Comment by hferentschik** [comment]
Thanks for the bug report. OOI, what would the output like like in a different language?

**Comment by davividal** [comment]
In German:

    Konfiguration der Schnittstelle "VirtualBox Host-Only Network"
        DHCP aktiviert:                       Nein
        IP-Adresse:                           192.168.56.1
        Subnetzpräfix:                        192.168.56.0/24 (Maske 255.255.255.0)
        Schnittstellenmetrik:                      25
        Statisch konfigurierte DNS-Server:    Keine
        Mit welchem Suffix registrieren:      Nur primäres
        Statisch konfigurierte WINS-Server:   Keine

In Brazilian Portuguese:

    Configuração da interface "Wi-Fi"
        DHCP habilitado:                         Sim
        Endereço IP:                           192.168.0.178
        Prefixo de Sub-rede:                        192.168.0.0/24 (máscara 255.255.255.0)
        Gateway Padrão:                      192.168.0.1
        Métrica de Gateway:                       0
        InterfaceMetric:                      55
        Servidores DNS configurados por DHCP:  192.168.0.1
        Registrar com o sufixo:           Somente principal
        Servidores WINS configurados por DHCP: Nenhum

**Comment by hferentschik** [comment]
Merged via pull request #345
