### ISSUE TITLE
Can't ping guest from host in OSX

### ISSUE THREAD

**Issue by lostinplace** [vagrant-landrush/landrush#47]
with configuration

````
config.landrush.enable
config.vm.box = "oracleLinux64"
config.vm.box_url = "http://kickstart.boston.zipcar.com/oracle_install/oracle.box"
config.vm.hostname = "oracle.vagrant.dev"
config.landrush.host 'static1.example.com', '1.2.3.4'
````

dig responds by correctly identifying the ip for oracle.vagrant.dev and static1.example.com

however ping, nslookup, and host are all unable to recognize the hostname
further, resolv.conf does not reflect localhost as a used DNS

wat do?

**Comment by njam** [comment]
I'm considering this resolved.

Caching in `mDNSResponder` is sometimes an issue still though.
