### ISSUE TITLE
Use system DNS servers for upstream_servers default?

### ISSUE THREAD

**Issue by njam** [vagrant-landrush/landrush#60]
Copying @amfranz from https://github.com/phinze/landrush/pull/57#issuecomment-40389634

> In my opinion, both things should happen: change the default value for the `upstream_servers`  setting to `RubyDNS::System::nameservers` as well as change landrush's DNS server logic to never delegate queries for `.vagrant.dev` upstream but rather respond with "domain not found" if no match is found.
> 
> When I configure landrush to use the system DNS servers, I observe delays when answering DNS queries and landrush crashes sometimes. I watched the network traffic with wireshark, here is what I found:
> - Queries for `*.vagrant.dev` that landrush can not answer and therefore delegates upstream trigger a query loop between dnsmasq and landrush (one delegates to the other, continuously).
> - Queries for `*.vagrant.dev` that landrush can answer seem to work initially, but sometimes also trigger a query loop if the DNS client sends a IPv6 AAAA query in addition to the A query (because landrush always delegates the AAAA query, which then loops).
> - Sometimes landrush crashes with `Malformed message smaller than two bytes received` in `rubydns-0.7.0/lib/rubydns/handler.rb:112`. I don't know the reason for this.

**Comment by bexelbie** [comment]
We should add this as an option ala `config.landrush.upstream host-system`

**Comment by bexelbie** [comment]
We should also consider an option for turning off upstream entirely.  This would require that VMs get a proper `/etc/resolv.conf` ... perhaps `config.landrush.upstream disabled` ?

**Comment by njam** [comment]
I'm not using landrush anymore. Feel free to reopen if you still want this.
