### ISSUE TITLE
Tag as v1.0.0 and beyond

### ISSUE THREAD

**Issue by pda** [vagrant-landrush/landrush#67]
As people are using this out in the wild, it'd be great to tag a v1.0.0 release, and follow [semver](http://semver.org/) from there.

See also: https://github.com/ioquatix/rubydns/issues/28

**Comment by bexelbie** [comment]
This is good idea.  There are some folks work on some larger patches at the moment.  Let's see how those go over the next few weeks along with the test @loquatix mentioned.  Then I think we can push a 1.0.0

**Comment by ioquatix** [comment]
RubyDNS 1.0.x is stable. RubyDNS 2.0.x is a bit unstable and depends on Celluloid::DNS which isn't released officially yet. The public API didn't change, just the implementation moved around a bit.

**Comment by bexelbie** [comment]
@ioquatix Does Ruby DNS 1.0 or 2.0 address the fork() issue, #16, on Windows?

**Comment by ioquatix** [comment]
Unfortunately no not at this point in time.

**Comment by hferentschik** [comment]
Version 1.0.0 is released now and moving forward we will apply semantic versioning.
