### ISSUE TITLE
Landrush doesn't register VMs on Vagrant 1.6

### ISSUE THREAD

**Issue by bilco105** [vagrant-landrush/landrush#68]
Installed landrush plugin and enabled within the Vagrantfile. 

I have two virtual machines which I'm setting hostnames for, however, when I do a `vagrant up`, landrush doesn't run.

Running `vagrant landrush vms` also returns 'No Dependant VMs'

This is on, Vagrant 1.6.1 and landrush 0.13.1

**Comment by njam** [comment]
Landrush works with Vagrant 1.7 and I think also 1.8.
Please reopen if you experience further problems.
