### ISSUE TITLE
unable to install on vagrant 1.6.3

### ISSUE THREAD

**Issue by hslee16** [vagrant-landrush/landrush#72]
complains about eventmachine while running

vagrant plug install landrush

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing eventmachine (1.0.3), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.

eventmachine gem installs manually without issues.

**Comment by njam** [comment]
Closing because outdated.
Landrush works on current OSX and with current Vagrant.
