### ISSUE TITLE
Guest can't resolve dns entries

### ISSUE THREAD

**Issue by tinco** [vagrant-landrush/landrush#93]
It says in the README I should file a bug, so here it is.

The guest is running:

    Linux db1 3.8.0-39-generic #57~precise1-Ubuntu SMP Tue Apr 1 20:04:50 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

The host is running:

    Linux phdevbak-1 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

    Vagrant 1.7.1

    $ vagrant landrush vms
     - web1
     - db2.unionstationapp.dev
     - db1.unionstationapp.dev
     - db1
     - web2
     - web1.unionstationapp.dev
     - web2.unionstationapp.dev
     - db2

When I `vagrant ssh db1` and then do `ping db2` or `ping db2.unionstationapp.dev` it says `unknown host db2`.

If I do `iptables -L` I don't see any rules related to DNS. I'm not sure if that's the correct way to debug it.

I am running other iptables commands in the chef provisioning scripts, though they shouldn't conflict, and they don't run on every `vagrant up`.

Hopefully you have a hint, this plugin looks like it's the perfect solution to our situation.

**Comment by phinze** [comment]
Hey there! Sorry you're hitting this problem.

The iptables rules are registered in the `nat` table, so have a look in `iptables -L -t nat` to see if the rules get registered. Ubuntu precise should work just fine.

I notice you're using the `unionstationapp.dev` domain. Did you override the default of `vagrant.dev` in your Vagrantfile?

Like this:

```ruby
config.landrush.tld = 'unionstationapp.dev`
```

Hopefully we can get this sorted for you quickly. :+1:

**Comment by d-snp** [comment]
Thanks for responding so quickly :)

There is something in the iptables, so that seems to work fine:

```
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             db1.unionstationapp.dev  tcp dpt:domain to:10.0.2.2:10053
DNAT       udp  --  anywhere             db1.unionstationapp.dev  udp dpt:domain to:10.0.2.2:10053
```

I don't really get the iptables rule though, why must the destination match db1.unionstationapp.dev? 

I configured the tld, here's an excerpt from the Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "phusion-open-ubuntu-12.04-amd64"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/ubuntu-12.04.3-amd64-vbox.box"
  config.ssh.forward_agent = true
  config.landrush.enabled = true
  config.landrush.tld = 'unionstationapp.dev'

  config.vm.provider :virtualbox do |vb|
     vb.gui = ENV['VAGRANT_LOG'] == 'INFO'
     vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define :db1 do |subconfig|
    subconfig.vm.network :private_network, ip: "192.168.2.22"
    subconfig.vm.network :forwarded_port, :guest => 22, :host => 7665
    subconfig.vm.hostname = 'db1.unionstationapp.dev'
    subconfig.vm.provision :shell do |s|
      s.path = "bootstrap_vagrant.sh"
      s.args = "db1 db1.#{us_domain} #{us_domain} #{ENCRYPTED_DATA_BAG_PASSWORD}"
    end
  end

  config.vm.define :db2 do |subconfig|
    subconfig.vm.network :private_network, ip: "192.168.2.23"
    subconfig.vm.network :forwarded_port, :guest => 22, :host => 7666
    subconfig.vm.hostname = 'db2.unionstationapp.dev'
    subconfig.vm.provision :shell do |s|
      s.path = "bootstrap_vagrant.sh"
      s.args = "db2 db2.#{us_domain} #{us_domain} #{ENCRYPTED_DATA_BAG_PASSWORD}"
    end
  end
```

**Comment by phinze** [comment]
Ok thanks for the extra info.

You're correct - those iptables rules don't look right. It looks like the source/destination might be flipped. I'm double checking locally to see...

**Comment by phinze** [comment]
Ah ok - I think you might have a bit of IP address overlapping. Landrush attempts to hijack any traffic on port 53 destined for what it determines to be the configured DNS server, which it determines by parsing `/etc/resolv.conf` and grabbing the first `nameserver` IP address it finds.

So you can add a `-n` to your `iptables` command and see the IP addresses instead of the domain names, and then check the contents of `/etc/resolv.conf` - does that give us any clues to what might be happening here?

As an example, I get an `eth0` with an IP address of `192.168.44.210` and a `resolv.conf` populated with `192.168.44.1` (which is the address of the DNS server on vmware_fusion). And here is my nat table:

```
vagrant@precise64:~$ sudo iptables -n -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DNAT       tcp  --  0.0.0.0/0            192.168.44.2         tcp dpt:53 to:192.168.44.1:10053
DNAT       udp  --  0.0.0.0/0            192.168.44.2         udp dpt:53 to:192.168.44.1:10053

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

**Comment by d-snp** [comment]
There's some weird stuff still going on.. maybe iptables isn't active or something? The rules do seem to be correct:

```
$ sudo iptables -L -t nat -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            127.0.1.1            tcp dpt:53 to:10.0.2.2:10053
DNAT       udp  --  0.0.0.0/0            127.0.1.1            udp dpt:53 to:10.0.2.2:10053

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination  
```
```
$ cat /etc/resolv.conf 
nameserver 127.0.1.1
```
But when I do:
```
$ telnet 127.0.1.1 53
Trying 127.0.1.1...
^C
```
It hangs forever. This works though:
```
$ telnet 10.0.2.2 10053
Trying 10.0.2.2...
Connected to 10.0.2.2.
```

So if the iptables rule would do like it says it does, it would rewrite traffic and at least reach some open port, but it never does.

**Comment by d-snp** [comment]
This is not really related I guess, but RubyDNS doesn't like it when you telnet into it and don't close the session neatly:

```
[landrush] Daemon status: crashed
Dumping daemon crash log:
=== Daemon Exception Backtrace @ 2015-01-06 11:58:24 +0100 ===
RubyDNS::LengthError: Unprocessed data remaining (68 bytes unprocessed)
/home/tinco/.vagrant.d/gems/gems/rubydns-0.7.3/lib/rubydns/handler.rb:142:in `unbind'
/home/tinco/.vagrant.d/gems/gems/eventmachine-1.0.4/lib/eventmachine.rb:1449:in `event_callback'
/home/tinco/.vagrant.d/gems/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/home/tinco/.vagrant.d/gems/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/home/tinco/.vagrant.d/gems/gems/rubydns-0.7.3/lib/rubydns.rb:41:in `run_server'
/home/tinco/.vagrant.d/gems/gems/landrush-0.15.3/lib/landrush/server.rb:51:in `run'
/home/tinco/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:92:in `block in start'
/home/tinco/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `fork'
/home/tinco/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `start'
/home/tinco/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/base.rb:129:in `start'
/home/tinco/.vagrant.d/gems/gems/landrush-0.15.3/lib/landrush/action/setup.rb:49:in `start_server'
/home/tinco/.vagrant.d/gems/gems/landrush-0.15.3/lib/landrush/action/setup.rb:23:in `pre_boot_setup'
/home/tinco/.vagrant.d/gems/gems/landrush-0.15.3/lib/landrush/action/setup.rb:8:in `block in call'
/home/tinco/.vagrant.d/gems/gems/landrush-0.15.3/lib/landrush/action/common.rb:22:in `handle_action_stack'
/home/tinco/.vagrant.d/gems/gems/landrush-0.15.3/lib/landrush/action/setup.rb:7:in `call'
```

**Comment by d-snp** [comment]
Sorry to bother you again, but how do you test the gem in vagrant before pushing it to rubygems? I tried running my own gem server and doing vagrant plugin install landrush --plugin-source http://0.0.0.0.8808, with a 0.15.4 landrush gem installed but it keeps ignoring the gem and installing 0.15.3 from rubygems instead.

**Comment by phinze** [comment]
> how do you test the gem in vagrant before pushing it to rubygems?

My way is a bit hacky but it works, dive into `~/.vagrant.d/gems/gems`, moved the installed `landrush-X.Y.Z` directory out of the way, and symlink your working dir into that spot. :grinning:

**Comment by d-snp** [comment]
Haha, that's exactly the sort of solution I was looking for. Since I had updated some dependencies, the slightly less hacky but still hacky solution was this: `gem install -i ~/.vagrant.d/gems/ pkg/landrush-0.15.4.gem`

**Comment by d-snp** [comment]
Just logging some things I tried out:

  - upgrading to vagrant 1.7.1 depency didn't fix it
  - upgrading to latest rubydns didn't fix it

It seems to really be a problem with my VM guest configuration. The iptables rules seem to be correct.

  - I  tried moving the iptables rules to the PREROUTING table instead of OUTPUT, instead of hanging forever it would just immediately refuse, so there seems to be at least something going on with iptables.
  - at some point I turned on ip_forwarding on the machine, I was surprised to see it was turned off, I would expect landrush to turn it on (as it enables the iptables rules) using this command: sysctl net.ipv4.ip_forward=1 , even though it was off before it didn't change any behaviour that I could see.

Next step: change the nameserver to something else than 127.0.1.1, maybe that's messing with something.

**Comment by phinze** [comment]
Hmm dang - this is a tricky one! On a virtualbox guest, 127.0.1.1 should be the address of your host - you should be able to ping it, ssh in, etc.

I wonder if it's something specific to your DNS configuration on the guest? Like does your `/etc/resolv.conf` look reasonable? And you're not doing anything fancy like dnsmasq on the guest or anything?

Maybe you already know this, but you can test queries to specific servers with `dig -p 10053 127.0.1.1 some.domain.tld`. Should be easier and less buggy than `telnet`.

**Comment by austinpray** [comment]
Sorry for the bump but I was able to resolve this issue by running:

```
vagrant landrush list
```

And then finding and removing some conflicting entries.

**Comment by tinco** [comment]
If no one else has this problem it can be closed, we've since moved to a development environment without virtual machines (only docker containers) and I haven't had any time to research landrush anymore to find out what was going wrong.
